language: ruby
cache:
  bundler: true
  directories:
    - build
    - .deps-cache
install: "bin/setup"
notifications:
  email: false
script: 'bundle exec middleman build --dependency-file=".deps-cache/deps.yml" --track-dependencies --only-changed'
sudo: false
